apiVersion: skaffold/v1
kind: Config
profiles:
  -
    name: deployment
    build:
      artifacts:
        - image: localhost:5000/openresty
          context: deployment/images/openresty
#        - image: localhost:5000/postgresql
#          context: deployment/images/postgresql
        - image: localhost:5000/redis
          context: deployment/images/redis
    deploy:
      kustomize:
        path: deployment/overlays/development

portForward:
 - resourceType: service
   resourceName: openresty
   namespace: default
   port: 80
   localPort: 8806