apiVersion: skaffold/v2beta11
kind: Config
profiles:
  -
    name: deployment
    build:
      artifacts:
        - image: localhost:5000/postgresql
          context: images/postgresql/
    deploy:
      kustomize:
        paths: 
          - overlays/development

#portForward:
# - resourceType: service
#   resourceName: postgresql
#   namespace: default
#   port: 5432
#   localPort: 5432