apiVersion: apps/v1
kind: Deployment
metadata:
  name: openresty
  labels:
    app: openresty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openresty
  template:
    metadata:
      labels:
        app: openresty
    spec:
      containers:
      - name: openresty
        image: localhost:5000/openresty
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: openresty
spec:
  type: ClusterIP
  selector:
    app: openresty
  ports:
    - name: http
      port: 80
      targetPort: 80

---
#apiVersion: v1
#kind: Service
#metadata:
#  name: openresty-external
#spec:
#  type: LoadBalancer
#  selector:
#    app: openresty
#  ports:
#    - name: http
#      port: 80
#      targetPort: 80