apiVersion: skaffold/v2beta11
kind: Config
profiles:
  -
    name: deployment
    build:
      artifacts:
        - image: localhost:5000/openresty
          context: images/openresty
#        - image: localhost:5000/postgresql
#          context: deployment/images/postgresql
        - image: localhost:5000/redis
          context: ../redis/images/redis
    deploy:
      kustomize:
        paths:
          - overlays/development
          - ../redis/overlays/development

portForward:
 - resourceType: service
   resourceName: openresty
   namespace: default
   port: 80
   localPort: 8806